### ISSUE TITLE
代码运行问题：ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by tyy-internetr** [WangRui5/PyHRMS#1]
import pandas as pd
from pyhrms import pyhrms as pms
path = 'G:/Mzmine_file_process/20190514-100ppb-test/20190514-FullmassAIF-100ppb-nce-20-02.mzML'
company = 'Thermo'
pms.multi_process(path,
                  company,
                  profile=True,
                  control_group=['lab_blank', 'methanol'],
                  processors=1,
                  ms2_analysis=True,
                  i_threshold=100,
                  filter_type=1
                  )
在运行代码第一步时遇见这类问题，请教下您，怎么解决

**Comment by SpecAnalyst** [comment]
你好，路径是文件夹路径，你给程序提供的是文件路径，只需要将path设置为‘G:/Mzmine_file_process/20190514-100ppb-test/’即可。

祝顺利，

王锐

tyy-internetr ***@***.***> 于2024年4月30日周二 19:32写道：

**Comment by tyy-internetr** [comment]
感谢感谢王老师，祝您生活愉快



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月30日 20:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [WangRui5/PyHRMS] 代码运行问题：ValueError: need at least one array to concatenate (Issue #1) |

你好，路径是文件夹路径，你给程序提供的是文件路径，只需要将path设置为‘G:/Mzmine_file_process/20190514-100ppb-test/’即可。

祝顺利，

王锐

tyy-internetr ***@***.***> 于2024年4月30日周二 19:32写道：

**Comment by tyy-internetr** [comment]
代码第一步运行后遇见的第二个问题：
Reading each excel file:  25%|██████████                              | 2/8 [00:00<00:00, 12.80it/s]Traceback (most recent call last):
  File "F:\python3.10\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-49c5de81b049>", line 9, in <module>
    pms.multi_process(path,
  File "F:\python3.10\lib\site-packages\pyhrms\pyhrms.py", line 441, in multi_process
    peak_alignment(files_excel)
  File "F:\python3.10\lib\site-packages\pyhrms\pyhrms.py", line 1425, in peak_alignment
    peak_ref = gen_ref(files_excel, rt_error=rt_error, mz_error=mz_error)
  File "F:\python3.10\lib\site-packages\pyhrms\pyhrms.py", line 1445, in gen_ref
    data1 = [pd.read_excel(file).loc[:, ['rt', 'mz']].values
  File "F:\python3.10\lib\site-packages\pyhrms\pyhrms.py", line 1445, in <listcomp>
    data1 = [pd.read_excel(file).loc[:, ['rt', 'mz']].values
  File "F:\python3.10\lib\site-packages\pandas\core\indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "F:\python3.10\lib\site-packages\pandas\core\indexing.py", line 1149, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "F:\python3.10\lib\site-packages\pandas\core\indexing.py", line 827, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "F:\python3.10\lib\site-packages\pandas\core\indexing.py", line 1191, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "F:\python3.10\lib\site-packages\pandas\core\indexing.py", line 1132, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "F:\python3.10\lib\site-packages\pandas\core\indexing.py", line 1327, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "F:\python3.10\lib\site-packages\pandas\core\indexes\base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "F:\python3.10\lib\site-packages\pandas\core\indexes\base.py", line 5842, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['rt', 'mz'], dtype='object')] are in the [columns]"

**Comment by SpecAnalyst** [comment]
你好，请问怎么称呼？

**Comment by SpecAnalyst** [comment]
涂同学你好，我猜测是因为你重新运行程序的时候里面的数据没有删除干净。如果要重新跑的话，建议把原来的excel都删除掉，这样就不会报错。

祝顺利，

王锐

**Comment by tyy-internetr** [comment]
新的报错，ValueError: No objects to concatenate
============================================================================
Third process...
============================================================================
                                                                            
  File "F:\python3.10\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-49c5de81b049>", line 9, in <module>
    pms.multi_process(path,
  File "F:\python3.10\lib\site-packages\pyhrms\pyhrms.py", line 464, in multi_process
    fold_change_filter(path, control_group=control_group, filter_type=filter_type)
  File "F:\python3.10\lib\site-packages\pyhrms\pyhrms.py", line 1779, in fold_change_filter
    blk_df = concat_alignment(blk_files)  # 生成所有blank的dataframe表
  File "F:\python3.10\lib\site-packages\pyhrms\pyhrms.py", line 1735, in concat_alignment
    final_data = pd.concat(data_to_concat, axis=1)
  File "F:\python3.10\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "F:\python3.10\lib\site-packages\pandas\core\reshape\concat.py", line 347, in concat
    op = _Concatenator(
  File "F:\python3.10\lib\site-packages\pandas\core\reshape\concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by SpecAnalyst** [comment]
一般来说，做高分辨质谱需要空白对照，所以默认的空白是control_group = ['methanol','lab_blank']，所以这一步你需要根据你自己的对照做修改。如果你的对照文件名称包括methanol，你就改成control_group = ['methanol']

**Comment by tyy-internetr** [comment]
匹配最后结果，会显示比对完成，但是没有生成任何文件，想请教一是我没有找到比对文件，还是没有找到化合物就不显示了

**Comment by tyy-internetr** [comment]
==========================
Matching started...
==========================
 
DIA columns: ['frag_DIA']
DDA columns: []
==========================
Matching complete!
==========================
